/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");
const path = require("path");

const app = express();

console.log(__dirname);

app.use(bodyParser.json());

let todos = [];

app.get("/todos", (req, res) => {
  fs.readFile(__dirname + "/todos.json", "utf-8", (err, data) => {
    if (err) {
      console.log("Error: ", err);
      return res.status(500).send("Internal Server Error");
    } else {
      todos = JSON.parse(data);
      console.log("Todos: ", todos);
      return res.json(todos);
    }
  });
});

app.get("/todos/:id", (req, res) => {
  fs.readFile(__dirname + "/todos.json", "utf-8", (err, data) => {
    todos = JSON.parse(data);
    const found = todos.find((todo) => {
      return todo.id === parseInt(req.params.id);
    });
    if (found) {
      console.log("Found");
      return res.status(200).json(found);
    } else {
      console.log("Not found");
      return res.status(404).send("Not Found");
    }
  });
});

app.post("/todos", (req, res) => {
  fs.readFile(__dirname + "/todos.json", "utf-8", (err, data) => {
    todos = JSON.parse(data);
    const newTodo = req.body;
    console.log(newTodo);
    const temp = {
      id: todos.length >= 1 ? todos[todos.length - 1].id + 1 : 1,
      title: newTodo.title,
      description: newTodo.description,
    };
    todos.push(temp);
    fs.writeFile(__dirname + "/todos.json", JSON.stringify(todos), (err) => {
      if (err) {
        return res.status(500).send("Internal Server Error");
      } else {
        console.log("Added");
        return res.status(201).json(temp);
      }
    });
  });
});

app.put("/todos/:id", (req, res) => {
  fs.readFile(__dirname + "/todos.json", "utf-8", (err, data) => {
    todos = JSON.parse(data);
    const found = todos.findIndex((todo) => {
      return todo.id === parseInt(req.params.id);
    });
    if (found !== -1) {
      console.log("Found");
      const newTodo = req.body;
      const temp = {
        id: parseInt(req.params.id),
        title: newTodo.title ? newTodo.title : todos[found].title,
        description: newTodo.description
          ? newTodo.description
          : todos[found].description, 
      };
      todos[found] = temp;
      fs.writeFile(__dirname + "/todos.json", JSON.stringify(todos), (err) => {
        if (err) {
          return res.status(500).send("Internal Server Error");
        } else {
          console.log("Updated");
          return res.status(200).json(temp);
        }
      });
    } else {
      console.log("Not found");
      return res.status(404).send("Not Found");
    }
  });
});

app.delete("/todos/:id", (req, res) => {
  fs.readFile(__dirname + "/todos.json", "utf-8", (err, data) => {
    todos = JSON.parse(data);
    const found = todos.findIndex((todo) => {
      return todo.id === parseInt(req.params.id);
    });
    if (found !== -1) {
      console.log("Found");
      todos.splice(found, 1);
      fs.writeFile(__dirname + "/todos.json", JSON.stringify(todos), (err) => {
        if (err) {
          return res.status(500).send("Internal Server Error");
        } else {
          console.log("Deleted");
          return res.status(200).send("Deleted");
        }
      });
    } else {
      console.log("Not found");
      return res.status(404).send("Not Found");
    }
  });
});

app.use((req, res, next) => {
  return res.status(404);
});

// app.listen(3000, (req, res) => {
//   console.log("Server is running on http://localhost:3000");
// });

module.exports = app;
